### ISSUE TITLE
Изменить модель API /booking

### ISSUE THREAD

**Issue by oagafonov** [Java-Java-Bootcamp/booking#18]
При вызове API /booking возвращать следующую модель

```

Booking:
      name: str
      rate: str
      cuisines: List of str
      averageBill: numeric
      availableReservations: List of Rerservation
  
Rerservation:
  start: text
  end: text
```
